Service for mapping public part of the certificate to the MF userid
zowe/zss pull request #224
Opened 2020-10-13 09:42 UTC by balhar-jakub

Copying the information

We have opened related PRs:
Documentation and setup - zowe/docs-site#1443
Testing - zowe/zowe-install-packaging#1713
Set up for the CICD pipeline: zowe/zowe-install-packaging#1714 and zowe/zowe-install-packaging#1726

As for the API ML the functionality is merged and hidden behind a feature flag.

Signed-off-by: Jakub Balhar <jakub.balhar@broadcom.com>

2020-10-14 09:04 UTC, ifakhrutdinov requested changes
Please fix the overlay and consider splitting return codes.

2020-10-14 09:32 UTC, balhar-jakub commented on c/certificateService.c
> +  if (rc == SUCCESS_RC && returnCode == SUCCESS_RC && returnCodeRacf == SUCCESS_RC && reasonCodeRacf == SUCCESS_RC) {
I changed the codes, I am only keeping the rc if you don't mind as it is part of the API and we expect it. I would have to remove it from other repositories as well.

2020-10-14 11:30 UTC, ifakhrutdinov approved these changes
LGTM, but I haven't tested this. @1000TurquoisePogs can someone verify this functionality?

2020-10-15 22:55 UTC, 1000TurquoisePogs commented
https://zowe.jfrog.io/zowe/libs-snapshot-local/org/zowe/zss/1.16.0-PR-224/zss-1.16.0-pr-224-4-20201014103628.pax is the build that was generated from this, and we can put it into the zowe-install* PRs as a way to test.

2020-10-15 22:55 UTC, 1000TurquoisePogs commented
https://zowe.jfrog.io/zowe/libs-snapshot-local/org/zowe/zss/1.16.0-PR-224/zss-1.16.0-pr-224-4-20201014103628.pax is the build that was generated from this, and we can put it into the zowe-install* PRs as a way to test.

2020-10-15 22:55 UTC, 1000TurquoisePogs commented
https://zowe.jfrog.io/zowe/libs-snapshot-local/org/zowe/zss/1.16.0-PR-224/zss-1.16.0-pr-224-4-20201014103628.pax is the build that was generated from this, and we can put it into the zowe-install* PRs as a way to test.

2020-11-02 20:38 UTC, merged