Feature/configurable cookiename
zowe/zss pull request #384
Opened 2021-12-08 19:27 UTC by 1000TurquoisePogs

Depends upon https://github.com/zowe/zowe-common-c/pull/262
Zowe v1 has an issue where you can't reach 2 unrelated ZSS from the same browser because they have identical cookie names and so one will overwrite the cookie value from the other, making only 1 valid at a time.
In order to fix this, something unique needs to be in the cookie name.
I implemented the same logic as seen in app-server which had the same problem and resolved it.
the cookie name has the suffix of the server port, unless HA is being used in which case the HA instance has a unique ID.
In both cases, the cookie name becomes unique enough that collision will no longer commonly happen.
This is a breaking change in that the cookie name has changed, so code that acts upon the cookie name will fail.

2021-12-13 04:46 UTC, lchudinov requested changes
The changes make sense to me, but please fix the way how you obtain env vars.

2021-12-13 04:46 UTC, lchudinov commented on c/zss.c
> +  if (haInstanceCount > 1) {
please check that `zoweInstanceId != NULL` as well

2021-12-13 04:46 UTC, lchudinov commented on c/zss.c
> +  char *zoweInstanceId = jsonObjectGetString(envConfig, "ZOWE_INSTANCE");
`envConfig` contains only `ZWED`-prefixed environment variables. Shouldn't you get other env vars with `getenv()`?

2021-12-14 03:39 UTC, lchudinov approved these changes
Now it looks good to me.

2021-12-14 09:06 UTC, ifakhrutdinov commented on c/zss.c
> +  char *haInstanceCountStr = getenv("ZWE_HA_INSTANCES_COUNT");
These calls can return `NULL`  if there are no such environmental variables.

2021-12-14 09:06 UTC, ifakhrutdinov commented on c/zss.c
> +    snprintf(cookieName, cookieLength, "%s.%s", SESSION_TOKEN_COOKIE_NAME, zoweInstanceId);
`snprintf` can fail, since this is related to security we might want to check it so the results of `generateCookieName` aren't unpredictable.

2021-12-14 09:06 UTC, ifakhrutdinov commented on c/zss.c
> +static char* generateCookieName(JsonObject *envConfig, int port) {
Do we want to have a counterpart function for cookie removal?

2021-12-14 09:06 UTC, ifakhrutdinov commented on c/zss.c
> +  char *cookieName = safeMalloc(cookieLength+1, "CookieName");
It's a good practice to check for `NULL`. Perhaps we should have a wrapper for `malloc`/`safeMalloc` which would abort if NULL is returned. We could use it for places where we don't want to continue execution if such a condition occurs.

2021-12-17 07:39 UTC, lchudinov requested changes
Please fix all places where cookie name is hardcoded e.g.  https://github.com/zowe/zss/blob/791de0b1376663a320998b5188b8edb7c6136f10/c/zss.c#L274
and test your PR carefully.

2022-02-04 14:27 UTC, closed without merging